server:
   port: 7075

keycloak:
  principal-attribute: preferred_username
  auth-server-url: http://localhost:8080/auth
  realm: ShababRealm
  resource: ShababClient
  public-client: true
  security-constraints:
      - auth-roles:
        - ShababUserRole
        security-collections:
        - name: secured
          patterns:
          - /customers/*
          - /visitor/*
      - auth-roles:
        - ShababAdminRole
        security-collections:
        - name: secured
          patterns:
          - /admin

  use-resource-role-mappings: true



